Tienda/Models/CommentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda.Models;


namespace peliculas.Controllers
{

    public class CommentController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();

        
        
        [ChildActionOnly] //This attribute means the action cannot be accessed from the browser's address bar
        public PartialViewResult _CommentsForMovie(int id = 0)
        {
            
            var comments = from c in db.Comments
                           where c.MovieId == id
                           select c;
            
            ViewBag.MovieId = id;
            return PartialView(comments.ToList());
        }

        //
        //POST: This action creates the comment when the AJAX comment create tool is used
        [HttpPost]
        public PartialViewResult _CommentsForMovie(Comment comment, int id = 0)
        {

            //Save the new comment
            comment.MovieId = id;
            db.Comments.Add(comment);
            db.SaveChanges();

            //Get the updated list of comments
            var comments = from c in db.Comments
                           where c.MovieId == id
                           select c;
            //Save the MovieId in the ViewBag because we'll need it in the view
            ViewBag.MovieId = id;
            //Return the view with the new list of comments
            return PartialView("_CommentsForMovie", comments.ToList());
        }

        //
        // GET: /Comment/_Create. A Partial View for displaying the create comment tool as a AJAX partial page update
        [Authorize]
        public PartialViewResult _Create(int id = 0)
        {
            //Create the new comment
            Comment newComment = new Comment();
            newComment.MovieId = id;
            newComment.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);

            ViewBag.MovieId = id;
            return PartialView("_CreateAComment");
        }



        //
        // GET: /Comment/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            PeliculaModel pelicula = db.peliculas.Find(comment.MovieId);
            comment.pelicula = pelicula;


            ViewBag.MovieId = comment.MovieId;
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
           
                     
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("details", "pelicula", new { id = comment.MovieId });
           
        }

    }
}

Tienda/Controllers/PeliculaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tienda.Models;
using PagedList;
using System.IO;

namespace Tienda.Controllers
{
    public class PeliculaController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();

        // GET: Pelicula
        private int paginacion = 10;
        
        public ActionResult Index(int pagina = 1)
        {
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult Lista(int pagina = 1)
        {
            if( Request.IsAjaxRequest())
            {
                return PartialView("_Resultados", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult ListaImagenes(int pagina = 1)
        {
            var paginacion = 18;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ResultadosImagenes", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult ListaPopOverImagenes(int pagina = 1)
        {
            var paginacion = 18;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ResultadosPopOverImagenes", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        // GET: Pelicula/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeliculaModel peliculaModel = db.peliculas.Find(id);
            if (peliculaModel == null)
            {
                return HttpNotFound();
            }
            return View(peliculaModel);
        }

        // GET: Pelicula/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pelicula/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Titulo,Fecha,Director,categoria,ruta,precio,descripcion")] PeliculaModel peliculaModel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);

                    path = "/content/imagenes/" + fileName;
                    peliculaModel.ruta = path;
                }
 
                db.peliculas.Add(peliculaModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(peliculaModel);
        }

        // GET: Pelicula/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeliculaModel peliculaModel = db.peliculas.Find(id);
            if (peliculaModel == null)
            {
                return HttpNotFound();
            }
            return View(peliculaModel);
        }

        // POST: Pelicula/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Titulo,Fecha,Director,categoria,ruta,precio,descripcion")] PeliculaModel peliculaModel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);

                    path = "/content/imagenes/" + fileName;
                    peliculaModel.ruta = path;
                }

                db.Entry(peliculaModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(peliculaModel);
        }

        // GET: Pelicula/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeliculaModel peliculaModel = db.peliculas.Find(id);
            if (peliculaModel == null)
            {
                return HttpNotFound();
            }
            return View(peliculaModel);
        }

        // POST: Pelicula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PeliculaModel peliculaModel = db.peliculas.Find(id);
            db.peliculas.Remove(peliculaModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RateProduct(int id, int rate)
        {

            int userId = 142;
            bool success = false;
            string error = "";
            try
            {
                success = CalificarPelicula(userId, id, rate);
            }
            catch (System.Exception ex)
            {
                error = ex.Message;
            }
            return Json(new { error = error, success = success, pid = id },
                JsonRequestBehavior.AllowGet);

        }

        private bool CalificarPelicula(int userId, int id, int rate)
        {
            PeliculaModel pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return false;
            }
            pelicula.Rate = rate;
            db.Entry(pelicula).State = EntityState.Modified;
            db.SaveChanges();
            return true;
        }

        public ContentResult AddFavorite(int id)
        {
            List<int> favorites = Session["Favorites"] as List<int>;
            if (favorites == null)
            {
                favorites = new List<int>();
            }
            favorites.Add(id);
            Session["Favorites"] = favorites;
            return Content("The movie has been added to your favorites", "text/plain", System.Text.Encoding.Default);
        }

        public ActionResult FavoritesSlideshow()
        {
            List<PeliculaModel> favPhotos = new List<PeliculaModel>();
            List<int> favoriteIds = Session["Favorites"] as List<int>;
            if (favoriteIds == null)
            {
                favoriteIds = new List<int>();
            }
            PeliculaModel currentMovie;

            foreach (int favID in favoriteIds)
            {
                currentMovie = db.peliculas.Find(favID);
                if (currentMovie != null)
                {
                    favPhotos.Add(currentMovie);
                }
            }

            return View("SlideShow", favPhotos);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tienda/Views/Pelicula/Create.cshtml
@model Tienda.Models.PeliculaModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pelicula",
    FormMethod.Post,
    new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PeliculaModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.categoria, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ruta, new { htmlAttributes = new { @class = "form-control" } })
                <img id="previewImg" width="100px" height="100px" />
                @Html.ValidationMessageFor(model => model.ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Imagen:
            </div>
            <div class="col-md-10">
                <input type="file" id="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

Tienda/Views/Pelicula/Delete.cshtml
@model Tienda.Models.PeliculaModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PeliculaModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tienda/Views/Pelicula/Details.cshtml
@model Tienda.Models.PeliculaModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@Styles.Render("~/Content/toastr")

<div>
    <h4>PeliculaModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ruta)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.ruta)*@
            <img title="@Model.Titulo" alt="@Model.Titulo" src="@Url.Content("~" + Model.ruta)" width="100px" height="100px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            Rate
        </dt>

        <dd>
            <span id="spanRate">
                @Html.DisplayFor(model => model.Rate)
            </span>
            @Html.Partial("_Rating", Model)

            <img src="~/Content/imagenes/loader.gif" style="display:none" id="imgLoader" />

            @Html.HiddenFor(m => m.Rate, new { id = "Rate" })
        </dd>

        <dd>
            <div id="addtofavorites">
                @Ajax.ActionLink("Add this Movie to your favorites",
        "AddFavorite",
        "Pelicula",
        new { id = Model.id },
        new AjaxOptions
        {
            UpdateTargetId = "addtofavorites",
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace
        })
            </div>
        </dd>

        @Html.Action("_CommentsForMovie", "Comment", new { id = Model.id })

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section scripts{
    <script src="@Url.Content("~/Scripts/rating.js")"></script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/toastr")

    <script>
        $(document).ready(function () {
            var pid = $("#Rate").val();
            $("input[type=radio][value='" + pid + "']").attr('checked', 'checked');

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-full-width",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "100",
                "hideDuration": "200",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

        });

        $(function () {
            $('.ratting-item').rating(function (vote, event) {
                var anchor = $(event.currentTarget);
                var pid = anchor.closest(".ratting-item").data("pid");
                var url = '@Url.Action("RateProduct", "Pelicula")';
                $("#Rate").val(vote);
                $("#spanRate").text(vote);

                $('.ratting-item[data-pid=' + pid + ']')
                    .next()
                    .text("Actualizando Calificacion...");

                //$("#imgLoader").show();

                var request = $.ajax({
                    url: url,
                    type: "GET",
                    data: { rate: vote, id: pid }
                });

                request.success(function (msg) {
                    console.log("sucess: " + msg);
                    if (msg.success) {
                        //$('.result').text("Listo");

                        toastr.options = {
                            "positionClass": "toast-top-center",
                        }

                        toastr.success('Calificación actualizada!');
                    }
                });

                request.error(function (msg) {
                    console.log("error:" + msg);
                    //$('.result').text(msg);
                    toastr.error('Ocurrió un error en la actualización');
                });

                request.complete(function () {
                    //console.log("complete");
                    //$('.ratting-item[data-pid=' + pid + ']')
                    //.next()
                    //.text("");
                    //$("#imgLoader").show();
                    $('.result').text("");
                    //toastr.info('Calificación actualizada!');
                });

            });

        });
    </script>
}

Tienda/Views/Pelicula/Edit.cshtml
@model Tienda.Models.PeliculaModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Pelicula",
    FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PeliculaModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.categoria, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ruta, new { htmlAttributes = new { @class = "form-control" } })
                <img id="previewImg" title="@Model.Titulo" alt="@Model.Titulo" src="@Url.Content("~" + Model.ruta)" width="100px" height="100px" />
                @Html.ValidationMessageFor(model => model.ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Imagen:
            </div>
            <div class="col-md-10">
                <input type="file" id="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextAreaFor(model => model.descripcion, new { rows = "5", cols = "150" })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

Tienda/Views/Pelicula/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Tienda.Models.PeliculaModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="pager" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }), PagedListRenderOptions.MinimalWithItemCountText)
</div>
<div id="peliculas">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].ruta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].descripcion)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Director)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoria)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ruta)*@
                    <img title ="@item.Titulo" alt="@item.Titulo" src="@Url.Content("~" + item.ruta)" width="100px" height="100px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>
</div>
<div class="pager" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }), PagedListRenderOptions.MinimalWithItemCountText)
</div>

Tienda/Views/Pelicula/Lista.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Tienda.Models.PeliculaModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="pager" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Lista", new { pagina }), PagedListRenderOptions.MinimalWithItemCountText)
</div>


@Html.Partial("_Resultados", Model)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tienda/Views/Pelicula/ListaImagenes.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Tienda.Models.PeliculaModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="container">
    @Html.Partial("_ResultadosImagenes", Model)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}